before:
  hooks:
    - go mod tidy
    - ./completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - '-s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}} -X main.BuiltBy=goreleaser'

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapcrafts:
  -
    id: jwt-decode-claims
    name: jwt-decode-claims
    publish: true
    summary: Simple tool to decode JSON Web token. No validation is included!.
    description: Just pass it as an argument jwt-decode-claims -t "ABeautifulToken" or pipe it in echo "ABeautifulToken" | jwt-decode-claims
    channel_templates:
      - stable
    grade: stable
    confinement: strict
    license: MIT
    base: core22
    apps:
      jwt-decode-claims:
        aliases:
          - jwt-decode
        command: jwt-decode
        completer: completions/jwt-decode.bash

nfpms:
  -
    id: jwt-decode
    package_name: jwt-decode
    homepage: https://github.com/jadolg/jwt-decode
    maintainer: Jorge Alberto Díaz Orozco (Akiel) <diazorozcoj@gmail.com>
    description: |-
      Simple tool to decode JSON Web token.
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    section: default
    priority: extra
    contents:
      - src: ./completions/jwt-decode.bash
        dst: /usr/share/bash-completion/completions/jwt-decode
        file_info:
          mode: 0644
      - src: ./completions/jwt-decode.fish
        dst: /usr/share/fish/vendor_completions.d/jwt-decode.fish
        file_info:
          mode: 0644
      - src: ./completions/jwt-decode.zsh
        dst: /usr/share/zsh/vendor-completions/_jwt-decode
        file_info:
          mode: 0644

brews:
  -
    name: jwt-decode
    homepage: "https://github.com/jadolg/jwt-decode"
    description: "Simple tool to decode JSON Web token."
    commit_author:
      name: jadolg
      email: diazorozcoj@gmail.com
    repository:
      token: "{{ .Env.GORELEASER_TAP_GITHUB_SECRET }}"
      owner: jadolg
      name: homebrew-tap
      pull_request:
         enabled: false
    directory: Formula
    install: |
      bin.install "jwt-decode"
