before:
  hooks:
    - go mod tidy
    - ./completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# .goreleaser.yaml
snapcrafts:
  -
    id: jwt-decode-claims
    name: jwt-decode-claims
    publish: true
    summary: Simple tool to decode JSON Web token. No validation is included!.
    description: Just pass it as an argument jwt-decode-claims -t "ABeautifulToken" or pipe it in echo "ABeautifulToken" | jwt-decode-claims
    channel_templates:
      - stable
    grade: stable
    confinement: strict
    license: MIT
    base: core22
    apps:
      jwt-decode-claims:
        command: jwt-decode
        completer: completions/jwt-decode-claims.bash
