name: jwt-decode-claims
version: '2.0.1'
summary: Simple tool to decode JSON Web token. No validation is included!.
description: Just pass it as an argument jwt-decode-claims -t "ABeautifulToken" or pipe it in echo "ABeautifulToken" | jwt-decode-claims

confinement: strict
base: core18
grade: stable

parts:
  jwt-decode-claims:
    plugin: go
    go-importpath: github.com/jadolg/jwt-decode
    source: https://github.com/jadolg/jwt-decode
    source-type: git
    build-packages:
      - gcc

architectures:
  - build-on: [ amd64, arm64, i386 ]

apps:
  jwt-decode-claims:
    command: bin/jwt-decode
